# permissions for end users to edit solrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: solr-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: solr-operator
    app.kubernetes.io/part-of: solr-operator
    app.kubernetes.io/managed-by: kustomize
  name: solr-editor-role
rules:
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - solrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - solrs/status
  verbs:
  - get
